[package]
name = "harness"
version = "0.1.0"
authors = ["The EinsteinDB Project Developers"]
license = "Apache-2.0"
keywords = []
repository = "https://github.com/whtcorpsinc/violetabft-rs/harness"
readme = "README.md"
homepage = "https://github.com/whtcorpsinc/violetabft-rs/harness"
description = "A testing harness for VioletaBFT."
categories = []
edition = "2018"

[features]
default = ["protobuf-codec", "violetabft/default-logger"]
protobuf-codec = ["violetabft/protobuf-codec"]
prost-codec = ["violetabft/prost-codec"]

# Make sure to synchronize updates with VioletaBFT.
[dependencies]
violetabft = { path = "..", default-features = false }
violetabft-proto = { path = "../proto", default-features = false }
rand = "0.7"
slog = "2.2"

[dev-dependencies]
criterion = "0.3"
fxhash = "0.2.1"
lazy_static = "1"
protobuf = "2"
regex = "1"
